import { Schema, model, type Document, type Model } from 'mongoose';

export interface ICalendarEvent extends Document {
  userId: string;
  title: string;
  description: string;
  date: string;
  endDate?: string | null;
  type: string;
  priority: string;
  color: string;
  materialId?: string | null;
  isAutoGenerated: boolean;
  isCompleted: boolean;
  createdAt: Date;
}

const calendarEventSchema = new Schema<ICalendarEvent>({
  userId: { type: String, required: true, index: true },
  title: { type: String, required: true },
  description: { type: String, default: '' },
  date: { type: String, required: true, index: true },
  endDate: { type: String, default: null },
  type: { type: String, default: 'custom' },
  priority: { type: String, default: 'medium' },
  color: { type: String, default: '#0E7C86' },
  materialId: { type: String, default: null },
  isAutoGenerated: { type: Boolean, default: false },
  isCompleted: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now },
});

calendarEventSchema.set('toJSON', {
  transform: (_doc, ret) => {
    const obj = ret as unknown as Record<string, unknown>;
    obj.id = ret._id.toString();
    delete obj._id;
    delete obj.__v;
    return obj;
  },
});

export const CalendarEvent: Model<ICalendarEvent> = model<ICalendarEvent>(
  'CalendarEvent',
  calendarEventSchema
);
