export interface User {
  id: string;
  name: string;
  email: string;
  company?: string;
  role: string;
}

export interface Material {
  id: string;
  name: string;
  description: string;
  unit: string;
  category: string;
  supplier: string;
  leadTimeDays: number;
  currentStock: number;
  totalStorageCapacity: number;
  dailyUsage: number;
  unitCost: number;
  stockPercentage: number;
  daysUntilStockout: number | null;
  nextResupplyDate?: string;
}

export interface ProductMaterial {
  materialName: string;
  quantity?: number;
  unit?: string;
}

export interface Product {
  id: string;
  name: string;
  description: string;
  sku: string;
  category: string;
  productionCycle: string;
  materials: ProductMaterial[];
}

export interface CalendarEvent {
  id: string;
  title: string;
  description: string;
  date: string;
  endDate?: string | null;
  type: string;
  priority: string;
  color: string;
  materialId?: string | null;
  materialName?: string | null;
  isAutoGenerated: boolean;
  isCompleted: boolean;
}

export interface ModelComparisonEntry {
  modelName: string;
  success: boolean;
  mape?: number;
  mae?: number;
  rmse?: number;
  confidence?: number;
  error?: string;
}

export interface Prediction {
  id: string;
  materialId: string;
  materialName: string;
  materialUnit?: string;
  materialCurrentStock?: number;
  predictedDailyUsage: number;
  estimatedStockoutDate?: string;
  recommendedResupplyDate?: string;
  recommendedOrderQuantity?: number;
  confidence?: number;
  trend: string;
  bestModel: string;
  modelsCompared: ModelComparisonEntry[];
}
